version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: varnish_proxy.Dockerfile
    env_file:
      - .env
    ports:
      - "1488:80"
    volumes:
      - ./temporary_storage:/home/api/application/temporary_storage
